CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(120) NOT NULL,
password VARCHAR(120) NOT NULL,
enabled INT NOT NULL,
PRIMARY KEY (id));

CREATE TABLE authorities (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(45) NOT NULL,
authority VARCHAR(45) NOT NULL,
PRIMARY KEY (id));